### PR TITLE
Tag intermediate docker images with commit hash

### PR DESCRIPTION
**Pull request by lennym**

### CODE REVIEW

**Comment by JoeChapman** [comment]
You missed this one https://github.com/UKHomeOffice/file-vault/blob/1b5f9a811b6c22756cfe25181807d56850b5ae3e/.drone.yml#L16.

Does this actually provide any value in this case? 
Because the image is never referenced by tag I don't see how tagging it is of any benefit.
In the case of an app with tests, the tag can be referenced so we know the correct app is being run against tests, but here we name the container but do not reference it again.

**Comment by lennym** [comment]
I didn't miss it. It's for PRs, so the built image never actually gets used for anything - I'm assuming that build step only exists so we know PRs will successfully build at all.

The tag is referenced again here: https://github.com/UKHomeOffice/file-vault/blob/1b5f9a811b6c22756cfe25181807d56850b5ae3e/.drone.yml#L36

**Comment by lennym** [comment]
TBH, it *might* not add any value at all in this case beyond just being a new `HEAD` so we can be absolutely sure we're getting a new image in R2R deployment.

**Comment by lennym** [comment]
Reading again I think we might be saying the same thing.

**Comment by JoeChapman** [comment]
It's not clear to me if that is creating the tag at `quay.io/ukhomeofficedigital/file-vault:${DRONE_COMMIT_SHA} ` or if it's referencing an existing image by tag.

**Comment by JoeChapman** [comment]
However, this is a problem with my knowledge of the subject and not _necessarily_ an issue with how we do things

**Comment by lennym** [comment]
I believe it is doing both. It's taking the existing local tag, and tagging it on quay (I think).

**Pull request merged**
